########
# settings

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

sass:
  sass_dir: css
  style: expanded

exclude:
- README.md
- .gitignore
- Gemfile
- Gemfile.lock
- _data/markdown_tools/README.md
- _data/markdown_tools_books/README.md


# safe: true
# lsi: false
